//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.UIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsSet
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime DateTime { get; set; }
        public int User_Id { get; set; }
        public int Game_Id { get; set; }
    
        public virtual GameSet GameSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
